version: 0.0
os: linux
files:
  - source: /index.html
    destination: /usr/share/nginx/html
    retain: true
    overwrite: true
    user: root
  - source: /nginx.conf
    destination: /etc/nginx/conf.d/
    retain: true
    overwrite: true
    user: root
# file_exists_behavior: OVERWRITE
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 300
      runas: root
    - location: scripts/start_server
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root

