version: 0.0
os: linux
files:
  - source: .
    destination: /var/www/html/assetz-serverside-3/
    user: root
    overwrite: true
# file_exists_behavior: OVERWRITE
hooks:
  BeforeInstall:
    - location: scripts/prepare.sh
      name: prepare_script
      runas: root
    - location: scripts/install.sh
      name: install_script
      runas: ec2-user
  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: ec2-user

